version: '2'
services:

  
#Nginx
  web:
    image: nginx:1.13.8
    cpu_shares: 30
    mem_limit: 512M
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./CityFarm/front:/code

#Tornado
  websocket:
    build: CityFarm
    command: ["python", "websocket.py"]
    cpu_shares: 30
    mem_limit: 512M
    ports:
      - "8888:8888"
    volumes:
      - ./CityFarm/code:/code
    depends_on:
      - redis

#Celery
  worker:
    build: CityFarm
    cpu_shares: 30
    mem_limit: 512M
    command: ["sh","run-worker.sh"]
    volumes:
      - ./CityFarm/code:/code
    depends_on:
      - rabbitmq
      - redis

#RabbitMQ
  rabbitmq:
    image: rabbitmq:3.6.15
    command: ["rabbitmq-server"]
    cpu_shares: 30
    mem_limit: 512M
    ports:
      - "15672:15672"
    volumes:
      - "./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins"

#Database
  redis:
    image: redis
    container_name: db_redis
    cpu_shares: 30
    mem_limit: 512M
    ports:
      - "6379:6379"