version: '2'
services:

#Python
  publisher:
    build: CityFarm
    volumes:
      - ./CityFarm/code:/code
    depends_on:
      - rabbitmq

#Python
  worker:
    build: CityFarm
    volumes:
      - ./CityFarm/code:/code
    depends_on:
      - rabbitmq
      - redis

#RabbitMQ
  rabbitmq:
    image: rabbitmq:3.6.15
    command: ["rabbitmq-server"]
    cpu_shares: 30
    mem_limit: 521M
    ports:
      - "15672:15672"
    volumes:
      - "./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins"

#Database
  redis:
    image: redis
    container_name: db_redis
    cpu_shares: 30
    mem_limit: 521M
    volumes:
      - ./scripts:/scripts
    ports:
      - "6379:6379"